local TableUtil = require(script.Parent.Parent.Util.TableUtil)

local customerList = {
	{
		id = "desperate_survivor",
		displayName = "Desperate Survivor",
		patience = 0.4,
		greed = 0.2,
		desperation = 0.95,
		knowledge = 0.15,
		temper = 0.3,
		scamBias = 0,
		minAskRatio = 0.72,
		openingLine = "Please... I need caps today.",
		reactions = {
			lowball_steal = { "Fine! Take it, I need food!", "Yes, just take it!", "Anything helps..." },
			lowball_crack = { "Maybe you're right about the value...", "I... I guess it isn't worth much." },
			lowball_offended = { "I'm desperate, not dumb!", "Don't push me.", "That's heartless." },
			accept = { "Thank you. I can eat tonight.", "Deal. Gods bless you.", "Yes. Take it." },
			counter = { "A little more? I'm begging.", "So close... help me out.", "I need just a bit more." },
			counter_close = { "Almost there. Please?", "One step higher and we're good." },
			reject_insult = { "I came here desperate, not stupid.", "Don't kick me when I'm down.", "That's cruel." },
			reject_low = { "I really need more than that.", "Come on, I'm hurting here.", "Can't go that low." },
			walkaway = { "Forget it. I'll try somewhere else.", "I can't do this anymore.", "I'm done begging." },
		},
	},
	{
		id = "shady_scammer",
		displayName = "Shady Scammer",
		patience = 0.75,
		greed = 0.9,
		desperation = 0.3,
		knowledge = 0.8,
		temper = 0.45,
		scamBias = 0.55,
		minAskRatio = 0.88,
		openingLine = "Trust me, this thing is priceless.",
		reactions = {
			lowball_offended = { "Nice try, chump.", "You think I'm stupid?", "Get out of my face." },
			lowball_crack = { "Okay, maybe I oversold it a little...", "Fine, it's not THAT rare." },
			accept = { "Ha! Sucker— I mean, pleasure doing business.", "Knew you'd see the value.", "Finally, someone smart." },
			counter = { "You're undervaluing history here.", "My price is firm-ish.", "Add more zeros." },
			counter_close = { "We're in the ballpark. Sweeten it.", "Don't be cheap now." },
			reject_insult = { "Insulting ME? Bold.", "You couldn't afford my reputation.", "Lowball detected." },
			reject_low = { "That's pawn shop robbery.", "Try again with respect.", "My time ain't free." },
			walkaway = { "Fine. I'll find a richer mark.", "Your loss, chief.", "Wasting a masterpiece here." },
		},
	},
	{
		id = "rich_collector",
		displayName = "Rich Collector",
		patience = 0.88,
		greed = 0.65,
		desperation = 0.1,
		knowledge = 0.92,
		temper = 0.2,
		scamBias = 0.05,
		minAskRatio = 0.92,
		openingLine = "I know what I brought. Don't insult me.",
		reactions = {
			lowball_offended = { "Outrageous.", "You bore me.", "Leave." },
			lowball_crack = { "Hmph. Perhaps you have a point.", "Don't let it go to your head." },
			accept = { "Acceptable. Don't scratch it.", "Fine. Wrap it nicely.", "I'll allow it." },
			counter = { "You're below market.", "I don't haggle like a drifter.", "Respect the piece." },
			counter_close = { "Closer. I haven't got all day.", "Nearly dignified." },
			reject_insult = { "Vulgar offer.", "Do I look desperate?", "How dare you." },
			reject_low = { "Amateur hour.", "My curator laughs at you.", "Try a yard sale." },
			walkaway = { "I'm leaving. Appalling.", "Waste of my afternoon.", "Good day." },
		},
	},
	{
		id = "robot_trader",
		displayName = "Robot Trader",
		patience = 0.95,
		greed = 0.5,
		desperation = 0.05,
		knowledge = 0.98,
		temper = 0.1,
		scamBias = 0,
		minAskRatio = 0.9,
		openingLine = "QUERY: OFFER AMOUNT IN CAPS.",
		reactions = {
			lowball_offended = { "OFFER REJECTED.", "INSUFFICIENT.", "TERMINATING." },
			lowball_crack = { "RECALCULATING VALUE...", "ANOMALY DETECTED IN PRICE." },
			accept = { "TRANSACTION: ACCEPTED.", "DEAL LOGGED.", "TRANSFER AUTHORIZED." },
			counter = { "OFFER BELOW THRESHOLD.", "RECALCULATING PRICE.", "INCREASE INPUT." },
			counter_close = { "DELTA: SMALL. ADJUST UPWARD.", "NEAR MATCH. REFINE OFFER." },
			reject_insult = { "ERROR: OFFER INSULTING.", "FLAGGED: BAD FAITH.", "DENIED." },
			reject_low = { "INSUFFICIENT CAPS.", "REJECTED.", "TRY AGAIN." },
			walkaway = { "SESSION TERMINATED.", "EXITING NEGOTIATION.", "NO DEAL." },
		},
	},
	{
		id = "mutant_drifter",
		displayName = "Mutant Drifter",
		patience = 0.22,
		greed = 0.35,
		desperation = 0.5,
		knowledge = 0.25,
		temper = 0.88,
		scamBias = 0.08,
		minAskRatio = 0.82,
		openingLine = "Trade quick. Sun burns.",
		reactions = {
			lowball_offended = { "Wrong move.", "You're done.", "Bye." },
			lowball_crack = { "Maybe junk. Hurry up.", "Could be worthless, fine." },
			accept = { "Good. Gone.", "Fine. Take it.", "Hurry." },
			counter = { "More. Sun's killing me.", "Higher. Now.", "Not enough." },
			counter_close = { "Almost. Speed it up.", "One bump. Quick." },
			reject_insult = { "You trying to die today?", "Bad idea.", "Angry now." },
			reject_low = { "Waste of time.", "Nope.", "Higher or I leave." },
			walkaway = { "Done. Too slow.", "Burning up. Bye.", "Forget you." },
		},
	},
	{
		id = "nervous_kid",
		displayName = "Nervous Kid",
		patience = 0.18,
		greed = 0.15,
		desperation = 0.75,
		knowledge = 0.1,
		temper = 0.78,
		scamBias = 0,
		minAskRatio = 0.74,
		openingLine = "Is... is this enough?",
		reactions = {
			lowball_steal = { "Okay! Please don't yell!", "Deal! I just want to go home!", "Yes, take it!" },
			lowball_offended = { "That's mean!", "Why would you say that?", "I'm leaving!" },
			lowball_crack = { "Maybe it's not worth much...", "I guess it could be junk..." },
			accept = { "Oh! Really? Thanks!", "Okay! Deal!", "My mom said be careful but... okay!" },
			counter = { "Um, a bit more?", "I-I think I need more...", "Sorry, is that okay?" },
			counter_close = { "So close, I think?", "Just a little more, please?" },
			reject_insult = { "That's... mean.", "Why would you say that?", "I'm gonna cry..." },
			reject_low = { "I was hoping for more...", "Please don't be mad.", "Maybe higher?" },
			walkaway = { "I can't do this!", "I'm leaving, sorry!", "Too scary..." },
		},
	},
	{
		id = "soldier",
		displayName = "Soldier",
		patience = 0.55,
		greed = 0.3,
		desperation = 0.38,
		knowledge = 0.55,
		temper = 0.72,
		scamBias = 0,
		minAskRatio = 0.86,
		openingLine = "Make it fair. I'm on a clock.",
		reactions = {
			lowball_offended = { "Not happening.", "Try that again.", "Done." },
			lowball_crack = { "Could be scrap. Clock's ticking.", "Might be worthless. Move on." },
			accept = { "Deal. Clock's ticking.", "Fair enough. Move.", "Sold. Next." },
			counter = { "Bump it. No games.", "Higher. I'm deployed soon.", "Not there yet." },
			counter_close = { "Close. Don't waste time.", "One step. Hurry." },
			reject_insult = { "Watch it.", "Try that again.", "Bad move." },
			reject_low = { "No.", "Higher.", "Stop lowballing." },
			walkaway = { "Done here.", "Out of time. Bye.", "Waste of mission." },
		},
	},
	{
		id = "junk_dealer",
		displayName = "Junk Dealer",
		patience = 0.72,
		greed = 0.78,
		desperation = 0.28,
		knowledge = 0.62,
		temper = 0.38,
		scamBias = 0.28,
		minAskRatio = 0.85,
		openingLine = "Bulk price if you buy today.",
		reactions = {
			lowball_offended = { "I know junk, pal.", "Beat it.", "Waste of time." },
			lowball_crack = { "Alright, it's not gold.", "Yeah, could be overpriced." },
			accept = { "Moving inventory. Good.", "You drive a hard deal.", "Cash talks." },
			counter = { "I got overhead, friend.", "Wholesale ain't charity.", "Add a few caps." },
			counter_close = { "We're close. Split the diff.", "One more nudge." },
			reject_insult = { "I know junk when I see you.", "Don't play me.", "Insulting." },
			reject_low = { "That's scrap pricing.", "Nah. Try again.", "Costs more than that." },
			walkaway = { "Take it to a landfill.", "No deal.", "Walked." },
		},
	},
	{
		id = "alien_tourist",
		displayName = "Alien Tourist",
		patience = 0.92,
		greed = 0.25,
		desperation = 0.15,
		knowledge = 0.35,
		temper = 0.12,
		scamBias = 0,
		minAskRatio = 0.8,
		openingLine = "Souvenir exchange? Yes?",
		reactions = {
			lowball_offended = { "Sad beeping.", "Not nice Earth custom.", "Confused and hurt." },
			lowball_crack = { "Maybe cheap souvenir?", "Value unclear. Interesting." },
			accept = { "Joy! Earth ritual complete.", "Trade successful!", "Caps received. Happy." },
			counter = { "More caps for memory?", "Confusion. Price higher?", "Adjust exchange?" },
			counter_close = { "Almost happy. Small boost?", "Near fair trade." },
			reject_insult = { "Rude Earth custom.", "Sad beeping.", "Not nice." },
			reject_low = { "Insufficient souvenir value.", "Need more caps?", "Hmm. Low." },
			walkaway = { "Leaving shop. Bored now.", "Trade cancelled.", "Bye Earth." },
		},
	},
	{
		id = "silent_stranger",
		displayName = "Silent Stranger",
		patience = 0.48,
		greed = 0.58,
		desperation = 0.2,
		knowledge = 0.82,
		temper = 0.4,
		scamBias = 0.18,
		minAskRatio = 0.88,
		openingLine = "...",
		reactions = {
			lowball_offended = { "...", "No.", "..." },
			lowball_crack = { "...", "Maybe.", "..." },
			accept = { "...", "Mm.", "Done." },
			counter = { "...", "Higher.", "No." },
			counter_close = { "...", "Closer." },
			reject_insult = { "...", "No.", "..." },
			reject_low = { "...", "Low.", "Try again." },
			walkaway = { "...", "Gone.", "..." },
		},
	},
}

local Customers = {
	List = customerList,
	ById = TableUtil.indexById(customerList, function(customer)
		return customer.id
	end),
}

function Customers.get(customerId: string)
	return Customers.ById[customerId]
end

function Customers.getRandom(rng: Random?)
	return TableUtil.pickRandom(Customers.List, rng)
end

return Customers
